name: Test PRs

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      id: cache
      with:
          path: env
          key: dep-${{ runner.os }}-${{ hashFiles('requirements.*') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m venv env
        env/bin/python -m pip install --upgrade pip
        env/bin/pip install -e .[test]

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        env/bin/flake8 . --exclude=env --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        env/bin/flake8 . --exclude=env --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Pytest and Coverage
      run: |
        env/bin/coverage run --branch -m pytest
        env/bin/coverage report
        env/bin/coverage html

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v1.0.0
      with:
          name: coverage-report
          path: htmlcov
